### ISSUE TITLE
Knack command broken

### ISSUE THREAD

**Issue by mudkippzs** [mudkippzs/fatebot#3]
Printing out knacks one letter at a time

**Comment by mudkippzs** [comment]
```

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dev/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/dev/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/dev/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: list indices must be integers or slices, not str
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "rival" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "z" is not found
Ignoring exception in command knacks:
Traceback (most recent call last):
  File "/home/dev/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 238, in knacks
    title, description_list, tables = search_knacks(term)
ValueError: not enough values to unpack (expected 3, got 2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dev/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/dev/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/dev/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: not enough values to unpack (expected 3, got 2)

```
